#switching
#
---
- hosts: webservers
  vars_files:
    - "vars/webserver.yml"

  tasks:
    - name: adjust urls appropriately
      include: tasks/adjust_urls.yml

    - name: Ensure wp_admin password is set correctly after import from production or staging db
      shell: wp-cli user --allow-root --no-color --path="{{wordpress_installs[0].path}}" update "{{wordpress_installs[0].admin_name}}" --user_pass="{{wordpress_installs[0].admin_password}}"

- hosts: loadbalancer
  roles:
    - role: loadbalancer
      TLS_EMAIL: 'the-mast@thoughtworks.com'
      SITE_DOMAIN: 'themastonline.com'

  tasks:
    - name: restart caddy
      service: name=caddy state=restarted
