---
- name: install caddy
  shell: curl https://getcaddy.com | bash -s ratelimit,expires
  args:
    creates: /usr/local/bin/caddy

- name: ensure correct permissions on caddy bin
  file:
    path: /usr/local/bin/caddy
    owner: root
    group: root
    mode: 0755

- name: allow caddy to bind to privileged ports
  capabilities:
    path: /usr/local/bin/caddy
    capability: cap_net_bind_service+ep
    state: present

- name: create home directory for caddy
  file:
    path: /var/www
    owner: www-data
    group: www-data
    mode: 0555
    state: directory

- name: add www-data group
  group:
    name: www-data
    gid: 33

- name: add www-data user
  user:
    name: www-data
    uid: 33
    group: www-data
    home: /var/www
    shell: /usr/sbin/nologin
    system: yes

- name: create etc dir for caddy
  file:
    path: /etc/caddy
    state: directory
    owner: root
    group: www-data

- name: create ssl dir for caddy
  file:
    path: /etc/ssl/caddy
    state: directory
    owner: www-data
    group: root
    mode: 0770

- name: template the Caddyfile
  template:
    dest: /etc/caddy/Caddyfile
    src: Caddyfile.j2
    owner: www-data
    group: www-data
    mode: 0444

- name: install as systemd service
  get_url:
    url: https://raw.githubusercontent.com/mholt/caddy/v0.9.5/dist/init/linux-systemd/caddy.service
    dest: /etc/systemd/system/caddy.service
    mode: 0700

- name: load into systemd to auto start on boot
  systemd:
    name: caddy
    enabled: yes
    daemon_reload: yes

- name: start caddy service
  systemd:
    name: caddy
    state: started
