---
- name: install dependencies
  apt: name=curl update_cache=yes

- name: common dependencies
  apt: name={{ item }} state=latest
  with_items:
    - iptables
    - fail2ban

- name: set correct timezone
  timezone:
    name: Africa/Lusaka

- name: disable password login for ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication no'
    line: 'PasswordAuthentication no'
    backrefs: true
  notify: restart sshd

- name: install & configure caddy
  include: caddy.yml

- name: ensure site directory exists for staging
  file:
    path: "/var/www/staging.{{ SITE_DOMAIN }}"
    state: directory

- name: add robots.txt for staging
  copy:
    dest: "/var/www/staging.{{ SITE_DOMAIN }}"
    src: robots.txt 
    owner: www-data
    group: www-data

